# Sử dụng image chứa JDK 17 và Maven
FROM maven:3.9.4-eclipse-temurin-17 AS builder

# Thư mục làm việc trong container
WORKDIR /app

# Expose cổng mặc định
EXPOSE 8080

# Lệnh mặc định khi chạy container (sẽ được override khi bạn chạy lệnh khác)
CMD ["bash"]
